### ISSUE TITLE
Removing a name from a scenario causes issue in server

### ISSUE THREAD

**Issue by Ryuna001** [UoaWDCC/VPS#73] opened 2023-04-25 00:30 UTC
When a user tries to remove the name from the scenario accidentally.  This bug also occurs if an individual scene name is null, and then the user backs out to the menu, and back in to edit again.  Perhaps the back end does not support a data with the text being null:

![Image](https://user-images.githubusercontent.com/100509811/234145738-a79e986f-7645-4367-9b2b-89a126a9853f.png)

- Add a safety check to see if the entered name is null and tell the user to enter a valid name and revert to the prior name

**Comment by djos192** [comment] 2023-04-25 00:31
When a user tries to remove the name from the scenario accidentally, the back end does not support a data with the text being null:

![Image](https://user-images.githubusercontent.com/100509811/234145738-a79e986f-7645-4367-9b2b-89a126a9853f.png)

- Add a safety check to see if the entered name is null and tell the user to enter a valid name and revert to the prior name

**Comment by John-Moore-UOA** [comment] 2023-05-03 03:12
Also there is the same bug when a scene name is 'null'.  If the user then exits to the menu, and tries to reload the particular scenario, the website wants to list the scenes, perhaps causing the bug in the case of scene blank names.

**Comment by arnard76** [comment] 2023-05-17 03:35
> When a user tries to remove the name from the scenario accidentally.

I did this 👇
1. navigated to deployed site
2. removed a scenario name
3. edited the scenario with no name
4. went back to home page

I didn't see an error in console or on the page
& the name had been reverted. 

https://github.com/UoaWDCC/VPS/assets/78939786/e58b0ff5-b138-410e-b8cd-c847a8778259

How was this error produced?

**Comment by John-Moore-UOA** [comment] 2023-05-17 05:02
Could you please try to reproduce that bug once again on the new commit?

I have no idea what that is.

Thanks

**Comment by John-Moore-UOA** [comment] 2023-05-17 06:49
This may be fixed on the null/name branch.

**Comment by arnard76** [comment] 2023-05-17 06:58
Cool, found the error again. This error doesn't show up in the frontend because of [this bugfix ](https://github.com/UoaWDCC/VPS/pull/80) but changing the name to empty string still displays an error in the backend: 

```
C:\Users\arnar\Desktop\Web Development\WDCC projects\vps project\VPS\backend\node_modules\mongoose\lib\document.js:2760
    this.$__.validationError = new ValidationError(this);
                               ^

ValidationError: Scenario validation failed: name: Path `name` is required.
    at model.Document.invalidate (C:\Users\arnar\Desktop\Web Development\WDCC projects\vps project\VPS\backend\node_modules\mongoose\lib\document.js:2760:32)
    at C:\Users\arnar\Desktop\Web Development\WDCC projects\vps project\VPS\backend\node_modules\mongoose\lib\document.js:2552:17
    at C:\Users\arnar\Desktop\Web Development\WDCC projects\vps project\VPS\backend\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errors: {
    name: ValidatorError: Path `name` is required.
        at validate (C:\Users\arnar\Desktop\Web Development\WDCC projects\vps project\VPS\backend\node_modules\mongoose\lib\schematype.js:1270:13)
        at C:\Users\arnar\Desktop\Web Development\WDCC projects\vps project\VPS\backend\node_modules\mongoose\lib\schematype.js:1253:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (C:\Users\arnar\Desktop\Web Development\WDCC projects\vps project\VPS\backend\node_modules\mongoose\lib\schematype.js:1198:14)
        at C:\Users\arnar\Desktop\Web Development\WDCC projects\vps project\VPS\backend\node_modules\mongoose\lib\document.js:2545:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      properties: {
        validator: [Function (anonymous)],
        message: 'Path `name` is required.',
        type: 'required',
        path: 'name',
        value: ''
      },
      kind: 'required',
      path: 'name',
      value: '',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Scenario validation failed'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Closed** 2024-04-25 01:25 UTC
Labels: bug
