### ISSUE TITLE
Enhance Timer Functionality

### ISSUE THREAD

**Issue by Harshal-D** [UoaWDCC/VPS#34] opened 2022-08-05 05:43 UTC
## Issue Description

Allow the user to have more control over the outcome of what happens when a timer ends.

For example:

- Image at the end of timer instead of just the modal popup.
    - E.G. at the end of a timer an image of as ECG pops up
- A PDF or document at the end of the timer
- Ability to restart the Scenario/scene
- Leave/close the scenario

## User Story

"As a lecturer, I would like to customise what happens at the end of a timer."

## MVP

Being able to change the outcome when a timer ends. For example being able to add an image, or being able to restart/close the scenario.

## Tasks

Describe the tasks in this story.

- [ ] Extend functionality to be able to add an image (or pdf etc...) or text at the end of a the timer.

**Comment by nickykay98** [comment] 2022-08-05 06:09
Note, a branch has already been created: https://github.com/UoaWDCC/VPS/tree/VPS-034/enhance-timer-functionality

**Comment by KW781** [comment] 2022-08-14 11:05
With regards to the document/PDF, what would it actually contain?

**Comment by nickykay98** [comment] 2022-08-15 06:14
@KW781 Sorry for the delay and lack of clarification!

The "user" as stated above would be the lecturer who wants to customise what happens at the end of a countdown. This customisation would most likely be able to be done when a lecturer is in the scene editor, so having more options there about what to present to a student once the timer finishes (beyond just the modal that pops up saying the time has run out and the buttons for the student to navigate)

So maybe the following things could be created in the scene editor:
- a text input option (to customise what text is shown instead of the "your time has run out" text or whatever it says when the timer runs out) 
- a file upload option for an image (doesn't matter what it contains, just assume it's something they want to show a student when the timer runs out that's relevant to that scene e.g. an image of a patient dying) that could show up in the modal as well if there was an image uploaded when the lecturer was in the scene editor

Hope that makes sense and you can make some progress on this before Wednesday! @Harshal-D Feel free to add any other clarification if there was anything missing/incorrect from the above

**Comment by KW781** [comment] 2022-08-15 06:30
Ah, I think I may have misinterpreted it then. I've made some progress, however what I've done is that I've expanded the modal menu that pops up to have options for restarting and also generating the PDF/document (but currently the PDF button doesn't do anything because I'm not sure what it's supposed to do). So now when the timer runs out, it has buttons for exiting, continuing without a timer, restarting, and generating a PDF. I've also inserted an image of an ECG into the modal.

Sorry for the misinterpretation, I assume that this was the desired functionality because the issue was tagged as a frontend task. If we're expanding the scene editor so that the user customises what happens at the end of the timer, then this would definitely require some backend work as well because then we'll have to store that information that inside the scenario object and store that into Mongo. I could try and have a go at that doing that, but the last sprint sort of showed me that I'm not all too familiar with the backend for this app.

**Comment by nickykay98** [comment] 2022-08-15 07:47
@KW781 I think the intention was to implement the customisability aspect in the scene editor, I'm not sure how useful it would be to have the student be able to upload a PDF and see an image of an ECG I'm afraid, though the restarting feature is a nice addition!

So sorry about this, I know we could have been clearer from the start (I suppose the frontend tag in this case was just to indicate where the expected behaviour could be seen, not necessarily where the work should be done) 😅 @Harshal-D something to note when we write future stories

You're right about storing the image in a scenario and in our DB, have a crack at it and see what you can do by Wednesday, we can always extend it into the next sprint and have Ray help you with the backend stuff too (don't worry, everyone finds that stuff difficult 😄)

**Comment by KW781** [comment] 2022-08-15 07:53
@nickykay98 No problem about that, I can have a crack at it. With regards to storing the image/document in the database, would Mongo store the image/document in the database itself? Or would it be a _link_ to the image/document?

**Comment by nickykay98** [comment] 2022-08-15 08:08
@KW781 Ideally the actual file itself within the database and associated with the scenario... the current way that uploaded images are stored (the ones that you upload yourself when clicking on the "Add Image" button when editing a scene I believe) is in a database in Firebase 

For example, here's one of the images I uploaded when creating my own scenario for the demo night slides: https://console.firebase.google.com/u/0/project/virtual-patient-simulator/storage/virtual-patient-simulator.appspot.com/files/~2F6285b537ea02ff2f64f4873d~2F6285b559ea02ff2f64f4875a

You could investigate how this image is linked to the corresponding scenario stored in MongoDB, then use that functionality to implement something similar for the modal specifically!

**Comment by KW781** [comment] 2022-09-05 23:21
@nickykay98 @Harshal-D 

Hey guys, I wanted to let you know of an issue I discovered with the saving of the image components in a scene while I was working on the firebase functionality.

Basically, I was trying to store the uploaded image that would be shown at the end of a scene timer into firebase, and after writing some code I wanted to check that the saving was still working properly for the images that are uploaded as components into the canvas (not the images that I was working on).

But I saw that it wasn't working properly, after adding an image onto the canvas and clicking 'Save & Close', it didn't appear when I played that scene. At first I thought my code must've broken it somehow.

But then I switched to the master branch, and the problem happened there as well. So it can't be to do with any code that I've written. Does this bug occur when you run the app on your end as well? I figured that this would probably be something good to resolve before I implement the saving of the uploaded modal image into firebase, because I'll probably do it in a similar way to the saving of the canvas image components.

**Comment by Harshal-D** [comment] 2022-09-06 05:30
@KW781 Thanks for bringing this up, will look into and see what's going on, hang tight.

**Comment by nickykay98** [comment] 2022-09-07 02:06
@KW781 @jfen445 At the meeting, Alfred suggested a possible solution to this

> @nickykay98 @Harshal-D
> 
> Hey guys, I wanted to let you know of an issue I discovered with the saving of the image components in a scene while I was working on the firebase functionality.
> 
> Basically, I was trying to store the uploaded image that would be shown at the end of a scene timer into firebase, and after writing some code I wanted to check that the saving was still working properly for the images that are uploaded as components into the canvas (not the images that I was working on).
> 
> But I saw that it wasn't working properly, after adding an image onto the canvas and clicking 'Save & Close', it didn't appear when I played that scene. At first I thought my code must've broken it somehow.
> 
> But then I switched to the master branch, and the problem happened there as well. So it can't be to do with any code that I've written. Does this bug occur when you run the app on your end as well? I figured that this would probably be something good to resolve before I implement the saving of the uploaded modal image into firebase, because I'll probably do it in a similar way to the saving of the canvas image components.

@KW781 @jfen445 At the meeting today, @retinfai suggested a solution to this, he'll reply to this comment later :)

**Comment by retinfai** [comment] 2022-09-07 03:57
Yeah, this is just in reference to the issue of the images not successfully uploading to firebase.

In meeting, although we don't explicitly know why, the promise created from the `save` and `saveAndClose` is not being resolved. We noticed that the `saveAndClose` function wasn't `async`. We found that `await saveScene()` forces the promise to be resolved before continuing, however this obviously causes the page to freeze while the image is being uploaded and then proceeds to exiting the page to scene selection. 

A possible work around for this, as proposed during the meeting, is to make use of the `LoadingPage` component that the previous dev team made to handle the awaiting of the save.

Hopefully it helps

**Comment by nickykay98** [comment] 2022-09-09 07:44
@KW781 @jfen445 ⬆️

**Comment by nickykay98** [comment] 2022-09-21 00:40
Continuing to be worked on in sprint 7

**Comment by nickykay98** [comment] 2022-10-25 00:50
@KW781 How are you going?

**Comment by KW781** [comment] 2022-10-25 11:46
Hey Nicholas! I'm so sorry, I had 3 assignments due over the weekend, and also a test I sat over the weekend, so I didn't have time to really investigate into the fetching of the firebase image.

I totally understand that you do need a working app to deliver to the clients, so what I've done for the time being is that I've opened a PR with the currently implemented enhanced timer functionalities already implemented. Since the only thing that hasn't been implemented is the fetching of the modal image from firebase, I've removed the file upload button from the editing page so that the user doesn't get confused what it's for, when that functionality hasn't been implemented yet.

Really sorry about this, although once you've merged this PR, could you keep the branch active so that maybe I could work on it at a later point in time? I do want to complete the fetching of the modal image maybe after exams, when I'll have more spare time (although I'm not sure if that can be delivered to the clients at that point in time).

One other thing I wanted to add is that for some reason I'm not passing the tests currently on the branch. I've fixed the issues from my end locally and am passing the tests, but for some reason that's not being reflected when committed here. Maybe you could look into this if you like? Otherwise I suppose you could just merge while ignoring the tests.

**Closed** 2022-10-25 23:10 UTC
Labels: enhancement, frontend

**Comment by nickykay98** [comment] 2022-10-25 23:33
Thanks for the PR and update @KW781! As discussed, let's stop development for now and document this as a thing to fix (both the image storing and the non-passing tests which don't seem to be a big issue for now if it's all still working), @Harshal-D  and I will get onto deploying the app
